name: documentation

trigger:
  batch: "true"
  branches:
    include:
      - "main"

resources:
  - repo: self

variables:
  DOCKER_BUILDKIT: 1
  containerRegistryReference: "Azure Container Registry"
  imageNames: ["documentation", "documentation-search"]

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: Build
    displayName: Build product documentation
    jobs:
      - job:
        displayName: Build product documentation
        steps:
          - checkout: self
            persistCredentials: "true"
            clean: "true"

          - task: Docker@2
            displayName: Login into Docker-Registry
            inputs:
              command: "login"
              containerRegistry: $(containerRegistryReference)

          - task: Docker@2
            displayName: Build and push container image
            inputs:
              command: "buildAndPush"
              repository: $(imageNames[0])
              containerRegistry: $(containerRegistryReference)
              tags: $(Build.BuildId)

          - task: Docker@2
            displayName: Build and push container image
            inputs:
              command: "buildAndPush"
              repository: $(imageNames[1])
              Dockerfile: "Dockerfile.search"
              containerRegistry: $(containerRegistryReference)
              tags: $(Build.BuildId)