####################################################################
## STAGE 1
####################################################################
FROM node:16.18.1 as builder

WORKDIR /app

COPY services/searchtool/package*.json /app/

RUN npm ci

COPY services/searchtool /app
RUN npm run build

CMD [ "node", "/app/build/index" ]