# Base info
site_name: ""

# Theme configuration
theme:
  custom_dir: overrides
  name: material 
  language: en

  logo: assets/logo-full-transparent.png
  palette:
    primary: rgb(19,61,139)
  font: 
    text: Mulish
  features:
   - navigation.tabs
  #   - navigation.sections
  #   - navigation.tracking
   - navigation.indexes
  #   - navigation.expand
  #   - navigation.top
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Stylesheet
extra_css:
  - stylesheets/extra.css

# # Page tree
nav:
  - Home: 'index.md'
  - Cognigy.AI Docs: 
    - Welcome: 
      - 'en/cognigyAI-docs/wellcome/cognigy_ai_documentation.md'
      - 'en/cognigyAI-docs/wellcome/platform_overview.md'
    - Notes: 
      - 'en/cognigyAI-docs/notes/release_notes.md'
    - Resources: 
      - Agents:
        - 'en/cognigyAI-docs/resources/agents/agents.md'
        - 'en/cognigyAI-docs/resources/agents/journeys.md'
        - 'en/cognigyAI-docs/resources/agents/tasks.md'
      - Build:
        - 'en/cognigyAI-docs/resources/build/build.md' 
        - 'en/cognigyAI-docs/resources/build/flows.md'
        - 'en/cognigyAI-docs/resources/build/lexicons.md'
        - 'en/cognigyAI-docs/resources/build/connections.md'
        - 'en/cognigyAI-docs/resources/build/nlu_connectors.md'
        - 'en/cognigyAI-docs/resources/build/functions.md'
      - Deploy: 
        - 'en/cognigyAI-docs/resources/deploy/deploy.md'
        - 'en/cognigyAI-docs/resources/deploy/endpoints.md'
        - 'en/cognigyAI-docs/resources/deploy/snapshots.md'
      - Test:  
        - 'en/cognigyAI-docs/resources/test/test.md'
        - 'en/cognigyAI-docs/resources/test/playbooks.md'
        - 'en/cognigyAI-docs/resources/test/logs.md'
      - Tweak:  
        - 'en/cognigyAI-docs/resources/tweak/tweak.md'
        - 'en/cognigyAI-docs/resources/tweak/intent_trainer.md'
      - 'en/cognigyAI-docs/resources/analytics.md'
      - Manage:  
        - 'en/cognigyAI-docs/resources/manage/manage.md'
        - 'en/cognigyAI-docs/resources/manage/settings.md'
        - 'en/cognigyAI-docs/resources/manage/localization.md'
        - 'en/cognigyAI-docs/resources/manage/tokens.md'
        - 'en/cognigyAI-docs/resources/manage/extensions.md'
        - 'en/cognigyAI-docs/resources/manage/members.md'
        - 'en/cognigyAI-docs/resources/manage/contact_profiles.md'
        - 'en/cognigyAI-docs/resources/manage/packages.md'
    - Flow Nodes:
      - 'en/cognigyAI-docs/flow_nodes/flow_nodes_overview.md'
      - 'en/cognigyAI-docs/flow_nodes/general_node_usage.md'
      - 'en/cognigyAI-docs/flow_nodes/dynamic_content_in_node.md'
      - Message:
        - 'en/cognigyAI-docs/flow_nodes/message/message.md'
        - 'en/cognigyAI-docs/flow_nodes/message/say.md'
        - 'en/cognigyAI-docs/flow_nodes/message/question.md'
        - 'en/cognigyAI-docs/flow_nodes/message/optional_question.md'
        - 'en/cognigyAI-docs/flow_nodes/message/send_email.md'
        - 'en/cognigyAI-docs/flow_nodes/message/send_email_notification.md'
        - 'en/cognigyAI-docs/flow_nodes/message/send_text.md'
        - 'en/cognigyAI-docs/flow_nodes/message/datepicker.md'
      - Logic:
        - 'en/cognigyAI-docs/flow_nodes/logic/logic.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/if.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/lookup.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/go_to.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/execute_flow.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/think.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/once.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/interval.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/stop_and_return.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/wait_for_input.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/sleep.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/reset_state.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/disable_slot_fillers.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/set_state.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/enable_slot_fillers.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/add_to_context.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/remove_from_context.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/switch_locale.md'
        - 'en/cognigyAI-docs/flow_nodes/logic/trigger_function.md'
      - Profile:
        - 'en/cognigyAI-docs/flow_nodes/profile/profile.md'
        - 'en/cognigyAI-docs/flow_nodes/profile/update_profile.md'
        - 'en/cognigyAI-docs/flow_nodes/profile/deactivat_profile.md'
        - 'en/cognigyAI-docs/flow_nodes/profile/delete_profile.md'
        - 'en/cognigyAI-docs/flow_nodes/profile/activate_profile.md'
        - 'en/cognigyAI-docs/flow_nodes/profile/merge_profile.md'
        - 'en/cognigyAI-docs/flow_nodes/profile/complete_goal.md'
      - Services: 
        - 'en/cognigyAI-docs/flow_nodes/services/services.md'
        - 'en/cognigyAI-docs/flow_nodes/services/ms_sql.md'
        - 'en/cognigyAI-docs/flow_nodes/services/mongo_db.md'
        - 'en/cognigyAI-docs/flow_nodes/services/http_request.md'
      - NLU: 
        - 'en/cognigyAI-docs/flow_nodes/nlu/nlu.md'
        - 'en/cognigyAI-docs/flow_nodes/nlu/copy_slots_to_text.md'
        - 'en/cognigyAI-docs/flow_nodes/nlu/add_lexicon_keyphrase.md'
        - 'en/cognigyAI-docs/flow_nodes/nlu/excute_cognigy_nlu.md'
        - 'en/cognigyAI-docs/flow_nodes/nlu/regex_slotfiller.md'
      - Code:
        - 'en/cognigyAI-docs/flow_nodes/code/code.md'
        - 'en/cognigyAI-docs/flow_nodes/code/actions.md'
        - 'en/cognigyAI-docs/flow_nodes/code/modules.md'
        - 'en/cognigyAI-docs/flow_nodes/code/channel_output.md'
        - 'en/cognigyAI-docs/flow_nodes/code/ai_default_channel_formats.md'
        - 'en/cognigyAI-docs/flow_nodes/code/analytics_data.md'
      - Voice Gateway: 
        - 'en/cognigyAI-docs/flow_nodes/voice_gateway/voice_gateway.md'
        - 'en/cognigyAI-docs/flow_nodes/voice_gateway/send_message.md'
        - 'en/cognigyAI-docs/flow_nodes/voice_gateway/set_session_params.md'
        - 'en/cognigyAI-docs/flow_nodes/voice_gateway/play_url.md'
        - 'en/cognigyAI-docs/flow_nodes/voice_gateway/handover_vg.md'
        - 'en/cognigyAI-docs/flow_nodes/voice_gateway/hangup.md'
        - 'en/cognigyAI-docs/flow_nodes/voice_gateway/send_meta_data.md'
        - 'en/cognigyAI-docs/flow_nodes/voice_gateway/call_recording.md'
        - 'en/cognigyAI-docs/flow_nodes/voice_gateway/agent_assist.md'
      - Other Nodes:
        - 'en/cognigyAI-docs/flow_nodes/other_nodes/other_nodes.md'
        - 'en/cognigyAI-docs/flow_nodes/other_nodes/log_message.md'
        - 'en/cognigyAI-docs/flow_nodes/other_nodes/overwrite_analytics.md'
    - NLU:
      - NLU overview: 
        - 'en/cognigyAI-docs/nlu/nlu_overview/nlu_overview.md'
        - 'en/cognigyAI-docs/nlu/nlu_overview/machine_learning_intents.md'
        - 'en/cognigyAI-docs/nlu/nlu_overview/annotations.md'
        - 'en/cognigyAI-docs/nlu/nlu_overview/intent_analyzer.md'
        - 'en/cognigyAI-docs/nlu/nlu_overview/rule_intents.md'
        - 'en/cognigyAI-docs/nlu/nlu_overview/intent_hierarchy.md'
        - 'en/cognigyAI-docs/nlu/nlu_overview/trigger_intent.md'
        - 'en/cognigyAI-docs/nlu/nlu_overview/intent_up_and_download.md'
        - 'en/cognigyAI-docs/nlu/nlu_overview/reject_intents.md'
      - Slot Mapping:
        - 'en/cognigyAI-docs/nlu/slot_mapping/slot_mapping.md'
        - 'en/cognigyAI-docs/nlu/slot_mapping/any_slots.md'
      - Attachments:
        - 'en/cognigyAI-docs/nlu/attachments/attachments.md'
        - 'en/cognigyAI-docs/nlu/attachments/attached_flows.md'
        - 'en/cognigyAI-docs/nlu/attachments/attached_lexicon.md'
      - External NLU:
        - 'en/cognigyAI-docs/nlu/external_nlu/external_nlu.md'
        - 'en/cognigyAI-docs/nlu/external_nlu/nlu_transformers.md'
        - 'en/cognigyAI-docs/nlu/external_nlu/no_nlu.md'
      - 'en/cognigyAI-docs/nlu/language_support.md'
      - 'en/cognigyAI-docs/nlu/nlu_warnings.md'
    - Tools:
      - User Menu:
        - 'en/cognigyAI-docs/tools/user_menu/user_menu.md'
        - 'en/cognigyAI-docs/tools/user_menu/my_profile.md'
        - 'en/cognigyAI-docs/tools/user_menu/access_control.md'
        - 'en/cognigyAI-docs/tools/user_menu/usage_statistics.md'
      - Interaction Panal: 
        - 'en/cognigyAI-docs/tools/interaction_panel/interaction_panel.md'
        - 'en/cognigyAI-docs/tools/interaction_panel/input.md'
        - 'en/cognigyAI-docs/tools/interaction_panel/state.md'
        - 'en/cognigyAI-docs/tools/interaction_panel/context.md'
        - 'en/cognigyAI-docs/tools/interaction_panel/profile.md'
      - CognigyScript: 'en/cognigyAI-docs/tools/cognigy_Script.md'
      - Analytics: 
        - 'en/cognigyAI-docs/tools/analytics/analytics.md'
        - 'en/cognigyAI-docs/tools/analytics/agents_analytics.md'
        - 'en/cognigyAI-docs/tools/analytics/odata_analytics_endpoint.md'
        - 'en/cognigyAI-docs/tools/analytics/analytics_concepts.md'
      - Hotkeys: 'en/cognigyAI-docs/tools/hotkeys.md'
      - Management UI: 'en/cognigyAI-docs/tools/management_ui.md'
      - Agent Handover: 'en/cognigyAI-docs/tools/agent_handover.md'
      - Live Agent: 'en/cognigyAI-docs/tools/live_agent.md'
    - Endpoints:
      - Overview: 'en/cognigyAI-docs/endpoints/overview.md'
      - Data Protection & Analytics: 'en/cognigyAI-docs/endpoints/data_protection_and_analytics.md'
      - Session Managemen: 'en/cognigyAI-docs/endpoints/session_management.md'
      - Handover Settings: 'en/cognigyAI-docs/endpoints/handover_settings.md'
      - Transformers:
        - 'en/cognigyAI-docs/endpoints/transformers/transformers.md'
        - 'en/cognigyAI-docs/endpoints/transformers/input_transformer.md'
        - 'en/cognigyAI-docs/endpoints/transformers/output_transformer.md'
        - 'en/cognigyAI-docs/endpoints/transformers/execution_finished_transformer.md'
        - 'en/cognigyAI-docs/endpoints/transformers/notify_transformer.md'
        - 'en/cognigyAI-docs/endpoints/transformers/inject_transformer.md'
      - Inject & Notify: 'en/cognigyAI-docs/endpoints/inject_and_notify.md'
      - Cognigy Webchat: 
        - 'en/cognigyAI-docs/endpoints/cognigy_webchat/cognigy_webchat.md'
        - 'en/cognigyAI-docs/endpoints/cognigy_webchat/deploy_a_webchat_endpoit.md'
        - 'en/cognigyAI-docs/endpoints/cognigy_webchat/webchat_features.md'
        - 'en/cognigyAI-docs/endpoints/cognigy_webchat/triggering_webchat_plugins.md'
        - 'en/cognigyAI-docs/endpoints/cognigy_webchat/integrated_demo_page.md'
      - Cognigy Voice Gateway: 'en/cognigyAI-docs/endpoints/cognigy_voice_gateway.md'
      - REST: 'en/cognigyAI-docs/endpoints/rest.md'
      - socket.io: 'en/cognigyAI-docs/endpoints/socket_io.md'
      - Webhock: 'en/cognigyAI-docs/endpoints/webhook.md'
      - Amazon Alexa: 'en/cognigyAI-docs/endpoints/amazon_alexa.md'
      - Dialogflow: 'en/cognigyAI-docs/endpoints/dialogflow.md'
      - Facebook Messenger: 'en/cognigyAI-docs/endpoints/fasebook_messenger.md'
      - Google Actions: 'en/cognigyAI-docs/endpoints/google_actions.md'
      - Intercom: 'en/cognigyAI-docs/endpoints/intercom.md'
      - LINE Messenger: 'en/cognigyAI-docs/endpoints/line_messenger.md'
      - Azure Bot Services: 'en/cognigyAI-docs/endpoints/azure_bot_services.md'
      - Microsoft Teams: 'en/cognigyAI-docs/endpoints/microsoft_teams.md'
      - RingCentral Engage: 'en/cognigyAI-docs/endpoints/ringcentral_engage.md'
      - Slack: 'en/cognigyAI-docs/endpoints/slack.md'
      - Sunshine Conversations: 'en/cognigyAI-docs/endpoints/sunshine_conversations.md'
      - Twillo: 'en/cognigyAI-docs/endpoints/twillio.md'
      - Userlike: 'en/cognigyAI-docs/endpoints/userlike.md'
      - Workplace by Facebook: 'en/cognigyAI-docs/endpoints/workplace_by_facebook.md'
    - Installation & Configuration:
      - Installation & Updating: 'en/cognigyAI-docs/installation_and_configuration/installation_and_updating.md'
      - Browser Requirements: 'en/cognigyAI-docs/installation_and_configuration/browser_requirements.md'
      - Single Sign-on using SAML 2.0: 'en/cognigyAI-docs/installation_and_configuration/single_sign_on_using_saml_20.md'
      - Single Sign-on using OpenID Connect: 'en/cognigyAI-docs/installation_and_configuration/single_sign_on_using_openid_connect.md'
      - IP Ranges Shared Envionments: 'en/cognigyAI-docs/installation_and_configuration/ip_ranges_shared_environments.md'
    - Developer Guides:
      - API Reference: 'en/cognigyAI-docs/developer_guides/api_reference.md'
      - Using the API: 'en/cognigyAI-docs/developer_guides/using_the_api.md'
      - Clients: 'en/cognigyAI-docs/developer_guides/clients.md'
    - Help & Cotact:
      - Get Help & Report Problems: 'en/cognigyAI-docs/help_and_contact/get_help_and_report_problems.md'
      - Community: 'en/cognigyAI-docs/help_and_contact/community.md'

  - Insights Docs: 'en/insights-docs/insights-docs.md'

plugins:
  - search 
  - i18n:
      default_language: en
      languages:
        de: Deutsch
      nav_translations:
        de:
          Topic1: Sujet1
          Topic2: Sujet2
      
# Localization
extra:
  alternate:
    - name: Default (en)
      link: ./
      lang: en
    - name: Deutsch
      link: ./de/
      lang: de
  generator: false

# Footer
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cognigy
      name: Cognigy on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/cognigy/
      name: Cognigy on Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/Cognigy
      name: Cognigy on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cognigy/mycompany/
      name: Cognigy on LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/Cognigy
      name: Cognigy on YouTube

# Markdoen Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  # - markdown_include.include:
  #     base_path: docs
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view

# Copyright
copyright: Copyright &copy; 2021 Cognigy.AI
