# Base info
site_name: ""

# Theme configuration
theme:
  custom_dir: overrides
  name: material 
  language: en

  logo: assets/logo-full-transparent.png
  palette:
    primary: rgb(19,61,139)
  font: 
    text: Mulish
  features:
   - navigation.tabs
  #   - navigation.sections
  #   - navigation.tracking
   - navigation.indexes
  #   - navigation.expand
  #   - navigation.top
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Stylesheet
extra_css:
  - stylesheets/extra.css

# # Page tree
nav:
  - Home: 'index.md'
  - Cognigy.AI Docs: 
    - Platform Overview: 'en/cognigyAI-docs/platform-overview/platform-overview.md'
    - Resources: 
      - Agents: 
        - Agents: 'en/cognigyAI-docs/resources/agents/agents.md'
        - Journeys: 'en/cognigyAI-docs/resources/agents/journeys.md'
        - Tasks: 'en/cognigyAI-docs/resources/agents/tasks.md'
      - Build:
        - Build: 'en/cognigyAI-docs/resources/build/build.md' 
        - Flows: 'en/cognigyAI-docs/resources/build/flows.md'
        - Lexicon: 'en/cognigyAI-docs/resources/build/lexicons.md'
        - Connections: 'en/cognigyAI-docs/resources/build/connections.md'
        - NLU Connectors: 'en/cognigyAI-docs/resources/build/nlu_connectors.md'
        - Functions: 'en/cognigyAI-docs/resources/build/functions.md'
      - Deploy: 
        - Deploy: 'en/cognigyAI-docs/resources/deploy/deploy.md'
        - Endpoints: 'en/cognigyAI-docs/resources/deploy/endpoints.md'
        - Snapshots: 'en/cognigyAI-docs/resources/deploy/snapshots.md'
      - Test:  
        - Test: 'en/cognigyAI-docs/resources/test/test.md'
        - Playbooks: 'en/cognigyAI-docs/resources/test/playbooks.md'
        - Logs: 'en/cognigyAI-docs/resources/test/logs.md'
      - Tweak:  
        - Tweak: 'en/cognigyAI-docs/resources/tweak/tweak.md'
        - Intent Trainer: 'en/cognigyAI-docs/resources/tweak/intent_trainer.md'
      - Analytics: 'en/cognigyAI-docs/resources/analytics/analytics.md'
      - Manage:  
        - Manage: 'en/cognigyAI-docs/resources/manage/manage.md'
        - Settings: 'en/cognigyAI-docs/resources/manage/settings.md'
        - Localization: 'en/cognigyAI-docs/resources/manage/localization.md'
        - Tokens: 'en/cognigyAI-docs/resources/manage/tokens.md'
        - Extensions: 'en/cognigyAI-docs/resources/manage/extensions.md'
        - Members: 'en/cognigyAI-docs/resources/manage/members.md'
        - Contact Profiles: 'en/cognigyAI-docs/resources/manage/contact_profiles.md'
        - Packages: 'en/cognigyAI-docs/resources/manage/packages.md'
    - Flow Nodes:
      - Flow Nodes Overview: 'en/cognigyAI-docs/flow_nodes/flow_nodes_overview/flow_nodes_overview.md'
      - General Node Usage: 'en/cognigyAI-docs/flow_nodes/general_node_usage/general_node_usage.md'
      - Daynamic Content in Nodes: 'en/cognigyAI-docs/flow_nodes/dynamic_content_in_node/dynamic_content_in_node.md'
      - Message:
        - Message: 'en/cognigyAI-docs/flow_nodes/message/message.md'
        - Say: 'en/cognigyAI-docs/flow_nodes/message/say.md'
        - Question: 'en/cognigyAI-docs/flow_nodes/message/question.md'
        - Optional Question: 'en/cognigyAI-docs/flow_nodes/message/optional_question.md'
        - Send Email: 'en/cognigyAI-docs/flow_nodes/message/send_email.md'
        - Send Email Notification: 'en/cognigyAI-docs/flow_nodes/message/send_email_notification.md'
        - Send Text: 'en/cognigyAI-docs/flow_nodes/message/send_text.md'
        - Datepicker: 'en/cognigyAI-docs/flow_nodes/message/datepicker.md'
      - Logic:
        - Logic: 'en/cognigyAI-docs/flow_nodes/logic/logic.md'
        - If: 'en/cognigyAI-docs/flow_nodes/logic/if.md'
        - Lookup: 'en/cognigyAI-docs/flow_nodes/logic/lookup.md'
        - Go To: 'en/cognigyAI-docs/flow_nodes/logic/go_to.md'
        - Execute Flow: 'en/cognigyAI-docs/flow_nodes/logic/execute_flow.md'
        - Think: 'en/cognigyAI-docs/flow_nodes/logic/think.md'
        - Once: 'en/cognigyAI-docs/flow_nodes/logic/once.md'
        - Interval: 'en/cognigyAI-docs/flow_nodes/logic/interval.md'
        - Stop and Return: 'en/cognigyAI-docs/flow_nodes/logic/stop_and_return.md'
        - Wait for Input: 'en/cognigyAI-docs/flow_nodes/logic/wait_for_input.md'
        - Sleep: 'en/cognigyAI-docs/flow_nodes/logic/sleep.md'
        - Reset State: 'en/cognigyAI-docs/flow_nodes/logic/reset_state.md'
        - Disable Slot Fillers: 'en/cognigyAI-docs/flow_nodes/logic/disable_slot_fillers.md'
        - Set State: 'en/cognigyAI-docs/flow_nodes/logic/set_state.md'
        - Enable Slot Fillers: 'en/cognigyAI-docs/flow_nodes/logic/enable_slot_fillers.md'
        - Add To Context: 'en/cognigyAI-docs/flow_nodes/logic/add_to_context.md'
        - Remove From Context: 'en/cognigyAI-docs/flow_nodes/logic/remove_from_context.md'
        - Switch Locale: 'en/cognigyAI-docs/flow_nodes/logic/switch_locale.md'
        - Trigger Function: 'en/cognigyAI-docs/flow_nodes/logic/trigger_function.md'
      - Profile:
        - Profile: 'en/cognigyAI-docs/flow_nodes/profile/profile.md'
        - Update Profile: 'en/cognigyAI-docs/flow_nodes/profile/update_profile.md'
        - Deactivate Profile: 'en/cognigyAI-docs/flow_nodes/profile/deactivat_profile.md'
        - Delete Profile: 'en/cognigyAI-docs/flow_nodes/profile/delete_profile.md'
        - Activate Profile: 'en/cognigyAI-docs/flow_nodes/profile/activate_profile.md'
        - Merge Profile: 'en/cognigyAI-docs/flow_nodes/profile/merge_profile.md'
        - Complete Goal: 'en/cognigyAI-docs/flow_nodes/profile/complete_goal.md'
      - Services: 
        - Services: 'en/cognigyAI-docs/flow_nodes/services/services.md'
        - MS SQL: 'en/cognigyAI-docs/flow_nodes/services/ms_sql.md'
        - Mongo DB: 'en/cognigyAI-docs/flow_nodes/services/mongo_db.md'
        - Http Request: 'en/cognigyAI-docs/flow_nodes/services/http_request.md'
      - NLU: 
        - NLU: 'en/cognigyAI-docs/flow_nodes/nlu/nlu.md'
        - Copy Slots to Context: 'en/cognigyAI-docs/flow_nodes/nlu/copy_slots_to_text.md'
        - Add Lexicon Keyphrase: 'en/cognigyAI-docs/flow_nodes/nlu/add_lexicon_keyphrase.md'
        - Execute Cognigy NLU: 'en/cognigyAI-docs/flow_nodes/nlu/excute_cognigy_nlu.md'
        - Regex Slotfiller: 'en/cognigyAI-docs/flow_nodes/nlu/regex_slotfiller.md'
      - Code:
        - Code: 'en/cognigyAI-docs/flow_nodes/code/code.md'
        - Action: 'en/cognigyAI-docs/flow_nodes/code/actions.md'
        - Modules: 'en/cognigyAI-docs/flow_nodes/code/modules.md'
        - Channel Output: 'en/cognigyAI-docs/flow_nodes/code/channel_output.md'
        - AI Default Channel Formats: 'en/cognigyAI-docs/flow_nodes/code/ai_default_channel_formats.md'
        - Analytics data: 'en/cognigyAI-docs/flow_nodes/code/analytics_data.md'
      - Voice Gateway: 
        - Voice Gateway: 'en/cognigyAI-docs/flow_nodes/voice_gateway/voice_gateway.md'
        - Send Message: 'en/cognigyAI-docs/flow_nodes/voice_gateway/send_message.md'
        - Set Session Params: 'en/cognigyAI-docs/flow_nodes/voice_gateway/set_session_params.md'
        - Play URL: 'en/cognigyAI-docs/flow_nodes/voice_gateway/play_url.md'
        - Handover (Voice Gateway): 'en/cognigyAI-docs/flow_nodes/voice_gateway/handover_vg.md'
        - Hangup: 'en/cognigyAI-docs/flow_nodes/voice_gateway/hangup.md'
        - Send Meta Data: 'en/cognigyAI-docs/flow_nodes/voice_gateway/send_meta_data.md'
        - Call Recording: 'en/cognigyAI-docs/flow_nodes/voice_gateway/call_recording.md'
        - Agent Assist: 'en/cognigyAI-docs/flow_nodes/voice_gateway/agent_assist.md'
      - Other Nodes:
        - Other Nodes: 'en/cognigyAI-docs/flow_nodes/other_nodes/other_nodes.md'
        - Log Message: 'en/cognigyAI-docs/flow_nodes/other_nodes/log_message.md'
        - Overwrite Analytics: 'en/cognigyAI-docs/flow_nodes/other_nodes/overwrite_analytics.md'
    - NLU:
      - NLU overview: 
        - NLU overview: 'en/cognigyAI-docs/nlu/nlu_overview/nlu_overview.md'
        - Machine learning Intents: 'en/cognigyAI-docs/nlu/nlu_overview/machine_learning_intents.md'
        - Annotations: 'en/cognigyAI-docs/nlu/nlu_overview/annotations.md'
        - Intent Analyzer: 'en/cognigyAI-docs/nlu/nlu_overview/intent_analyzer.md'
        - Rule Intents: 'en/cognigyAI-docs/nlu/nlu_overview/rule_intents.md'
        - Intent Hierarchy: 'en/cognigyAI-docs/nlu/nlu_overview/intent_hierarchy.md'
        - Trigger Intent: 'en/cognigyAI-docs/nlu/nlu_overview/trigger_intent.md'
        - Intent Up- and Download: 'en/cognigyAI-docs/nlu/nlu_overview/intent_up_and_download.md'
        - Reject Intents: 'en/cognigyAI-docs/nlu/nlu_overview/reject_intents.md'
      - Slot Mapping:
        - Slot Mapping: 'en/cognigyAI-docs/nlu/slot_mapping/slot_mapping.md'
        - Any Slots: 'en/cognigyAI-docs/nlu/slot_mapping/any_slots.md'
      - Attachments:
        - Attachments: 'en/cognigyAI-docs/nlu/attachments/attachments.md'
        - Attached Flow: 'en/cognigyAI-docs/nlu/attachments/attached_flows.md'
        - Attached Lexicon: 'en/cognigyAI-docs/nlu/attachments/attached_lexicon.md'
      - External NLU:
        - External NLU: 'en/cognigyAI-docs/nlu/external_nlu/external_nlu.md'
        - NLU Transformers: 'en/cognigyAI-docs/nlu/external_nlu/nlu_transformers.md'
        - No NLU: 'en/cognigyAI-docs/nlu/external_nlu/no_nlu.md'
      - Language Support: 'en/cognigyAI-docs/nlu/language_support/language_support.md'
      - NLU Warnings: 'en/cognigyAI-docs/nlu/nlu_warnings/nlu_warnings.md'

  - Insights Docs: 'en/insights-docs/insights-docs.md'

plugins:
  - search 
  - i18n:
      default_language: en
      languages:
        de: Deutsch
      nav_translations:
        de:
          Topic1: Sujet1
          Topic2: Sujet2
      
# Localization
extra:
  alternate:
    - name: Default (en)
      link: ./
      lang: en
    - name: Deutsch
      link: ./de/
      lang: de
  generator: false

# Footer
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cognigy
      name: Cognigy on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/cognigy/
      name: Cognigy on Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/Cognigy
      name: Cognigy on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cognigy/mycompany/
      name: Cognigy on LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/Cognigy
      name: Cognigy on YouTube

# Markdoen Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  # - markdown_include.include:
  #     base_path: docs
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view

# Copyright
copyright: Copyright &copy; 2021 Cognigy.AI
