site_name: Cognigy.AI
site_description: Documentation from Cognigy.AI products
site_url: https://dev-docs.cognigy.ai/
theme:
  name: material
  custom_dir: overrides
  palette:
  - scheme: default
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  font:
    text: Mulish
  features:
  - search.suggest
  - search.highlight
  - navigation.tabs
  - navigation.tracking
  - navigation.indexes
  - navigation.top
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  logo: assets/img/Cognigy-white.svg
  favicon: assets/img/favicon.png
  language: en
nav:
- Cognigy Products: index.md
- Languages:
  - en: /
  - de: /de/
- AI:
  - ai/platform-overview.md  #converted
  - Release Notes:
    - ai/release-notes.md #converted
  - Resources:
    - Agents:
      - ai/resources/agents/agents.md #converted
      - ai/resources/agents/journeys.md #converted
      - ai/resources/agents/tasks.md #converted
    - Build:
      - ai/resources/build/build.md #converted
      - ai/resources/build/flows.md #converted
      - ai/resources/build/lexicons.md #converted
      - ai/resources/build/connections.md #converted
      - ai/resources/build/NLUconnectors.md #converted
      - ai/resources/build/functions.md #converted
    - Deploy:
      - ai/resources/deploy/deploy.md #converted
      - ai/resources/deploy/endpoints.md #converted
      - ai/resources/deploy/snapshots.md #converted
    - Test:
      - ai/resources/test/test.md #converted
      - ai/resources/test/playbooks.md #converted
      - ai/resources/test/logs.md #converted
    - Tweak:
      - ai/resources/tweak/tweak.md #converted
      - ai/resources/tweak/intent-trainer.md #converted
    - Analytics:
      - ai/resources/analytics.md #converted
    - Manage:
      - ai/resources/manage/manage.md #converted
      - ai/resources/manage/settings.md #converted
      - ai/resources/manage/localization.md #converted
      - ai/resources/manage/tokens.md #converted
      - ai/resources/manage/extensions.md #converted
      - ai/resources/manage/members.md #converted
      - ai/resources/manage/contact-profiles.md #converted
      - ai/resources/manage/packages.md #converted
  -  Flow Nodes:
    - ai/flow-nodes/flow-nodes-overview.md
    - ai/flow-nodes/node-usage.md
    - ai/flow-nodes/dynamic-content.md
    - ai/flow-nodes/dynamic-node-fields.md
    - Message:
      - ai/flow-nodes/message/message.md
      - ai/flow-nodes/message/say.md
      - ai/flow-nodes/message/question.md
      - ai/flow-nodes/message/optional-question.md
      - ai/flow-nodes/message/send-email.md
      - ai/flow-nodes/message/send-email-notification.md
      - ai/flow-nodes/message/send-text.md
      - ai/flow-nodes/message/datepicker.md
    - Logic:
      - ai/flow-nodes/logic/logic.md
      - ai/flow-nodes/logic/if.md
      - ai/flow-nodes/logic/lookup.md
      - ai/flow-nodes/logic/go-to.md
      - ai/flow-nodes/logic/execute-flow.md
      - ai/flow-nodes/logic/think.md
      - ai/flow-nodes/logic/once.md
      - ai/flow-nodes/logic/interval.md
      - ai/flow-nodes/logic/stop-and-return.md
      - ai/flow-nodes/logic/wait-for-input.md
      - ai/flow-nodes/logic/sleep.md
      - ai/flow-nodes/logic/reset-state.md
      - ai/flow-nodes/logic/disable-slot-fillers.md
      - ai/flow-nodes/logic/set-state.md
      - ai/flow-nodes/logic/enable-slot-fillers.md
      - ai/flow-nodes/logic/add-to-context.md
      - ai/flow-nodes/logic/remove-from-context.md
      - ai/flow-nodes/logic/switch-locale.md
      - ai/flow-nodes/logic/trigger-function.md
    - Profile:
      - ai/flow-nodes/profile/profile.md
      - ai/flow-nodes/profile/update-profile.md
      - ai/flow-nodes/profile/deactivate-profile.md
      - ai/flow-nodes/profile/delete-profile.md
      - ai/flow-nodes/profile/activate-profile.md
      - ai/flow-nodes/profile/merge-profile.md
      - ai/flow-nodes/profile/complete-goal.md
    - Services:
      - ai/flow-nodes/services/services.md
      - ai/flow-nodes/services/ms-sql.md
      - ai/flow-nodes/services/mongo-db.md
      - ai/flow-nodes/services/http-request.md
    - NLU:
      - ai/flow-nodes/nlu/nlu.md
      - ai/flow-nodes/nlu/copy-slots-to-context.md
      - ai/flow-nodes/nlu/add-lexicon-keyphrase.md
      - ai/flow-nodes/nlu/execute-cognigy-nlu.md
      - ai/flow-nodes/nlu/regex-slotfiller.md
    - Code:
      - ai/flow-nodes/code/code.md
      - ai/flow-nodes/code/actions.md
      - ai/flow-nodes/code/modules.md
      - ai/flow-nodes/code/channel-output.md
      - ai/flow-nodes/code/AI-default-channel-formats.md
      - ai/flow-nodes/code/analytics-data.md
    - Voice Gateway:
      - ai/flow-nodes/vg/voice-gateway.md
      - ai/flow-nodes/vg/send-message.md
      - ai/flow-nodes/vg/set-session-params.md
      - ai/flow-nodes/vg/play-url.md
      - ai/flow-nodes/vg/handoverVG.md
      - ai/flow-nodes/vg/hangup.md
      - ai/flow-nodes/vg/send-meta-data.md
      - ai/flow-nodes/vg/call-recording.md
      - ai/flow-nodes/vg/agent-assist.md
    - Other Nodes:
      - Log Message: ai/flow-nodes/other-nodes/log-message.md
      - ai/flow-nodes/other-nodes/overwrite-analytics.md
      - ai/flow-nodes/other-nodes/set-rating.md
      - ai/flow-nodes/other-nodes/set-translation.md
      - ai/flow-nodes/other-nodes/request-rating.md
  - NLU:
    - NLU Overview: 
      - ai/nlu/nlu-overview/overview.md
      - ai/nlu/nlu-overview/ML-intents.md
      - ai/nlu/nlu-overview/annotations.md
      - ai/nlu/nlu-overview/intent-analyzer.md
      - ai/nlu/nlu-overview/rule-intents.md
      - ai/nlu/nlu-overview/intent-hierarchy.md
      - ai/nlu/nlu-overview/trigger-intent.md
      - ai/nlu/nlu-overview/intent-upload-download.md
      - ai/nlu/nlu-overview/reject-intents.md
    - Slot Mapping:
      - ai/nlu/slot-mapping/slot-mapping.md
      - ai/nlu/slot-mapping/any-slots.md
    - Attachments:
      - ai/nlu/attachments/attachments.md
      - ai/nlu/attachments/attached-flows.md
      - ai/nlu/attachments/attached-lexicons.md
    - External NLU:
      - ai/nlu/external-nlu/external-nlu.md
      - ai/nlu/external-nlu/nlu-transformers.md
      - ai/nlu/external-nlu/no-nlu.md
    - ai/nlu/language-support.md
    - ai/nlu/nlu-warnings.md
  - Tools:
    - User menu:
      - ai/tools/user-menu/user-menu.md #converted
      - ai/tools/user-menu/my-profile.md #converted
      - ai/tools/user-menu/access-control.md #converted
      - ai/tools/user-menu/usage-statistics.md #converted
    - Interaction Panel:
      - ai/tools/interaction-panel/interaction-panel.md #converted
      - ai/tools/interaction-panel/input.md #converted
      - ai/tools/interaction-panel/state.md #converted
      - ai/tools/interaction-panel/context.md #converted
      - ai/tools/interaction-panel/profile.md #converted
    - ai/tools/cognigy-script.md  #converted
    - Analytics:
      - ai/tools/analytics/analytics.md #converted
      - ai/tools/analytics/agents-analytics.md #converted
      - ai/tools/analytics/odata-analytics-endpoint.md #converted
      - ai/tools/analytics/analytics-concepts.md #converted
    - ai/tools/hotkeys.md #converted
    - ai/tools/managementUI.md #converted
    - ai/tools/agent-handover.md #converted
    - ai/tools/live-agent.md #converted
    - ai/tools/chatwoot-integration.md #converted
    - ai/tools/auto-localization.md #converted
    - ai/tools/real-time-translation.md #converted
  - Endpoints:
    - ai/endpoints/overview.md #converted
    - ai/endpoints/data-protection-and-analytics.md #converted
    - ai/endpoints/session-management.md #converted
    - ai/endpoints/handover-settings.md #converted
    - Transformers:
      - ai/endpoints/transformers/transformers.md #converted
      - ai/endpoints/transformers/input-transformer.md #converted
      - ai/endpoints/transformers/output-transformer.md #converted
      - ai/endpoints/transformers/execution-finished-transformer.md #converted
      - ai/endpoints/transformers/notify-transformer.md #converted
      - ai/endpoints/transformers/inject-transformer.md #converted
    - ai/endpoints/inject-and-notify.md #converted
    - Cognigy Webchat:
      - ai/endpoints/webchat/webchat.md #converted
      - ai/endpoints/webchat/deploy-webchat-endpoint.md #converted
      - ai/endpoints/webchat/webchat-features.md #converted
      - ai/endpoints/webchat/triggering-webchat-plugins.md #converted
      - ai/endpoints/webchat/integrated-demo-page.md #converted
    - ai/endpoints/cognigy-vg.md #converted
    - ai/endpoints/rest.md #converted
    - ai/endpoints/socketio.md #converted
    - ai/endpoints/webhook.md #converted
    - ai/endpoints/amazon-alexa.md #converted
    - ai/endpoints/dialogflow.md #converted
    - ai/endpoints/facebook-messenger.md #converted
    - ai/endpoints/google-actions.md #converted
    - ai/endpoints/intercom.md #converted
    - ai/endpoints/line-messenger.md #converted
    - ai/endpoints/azure-bot-services.md #converted
    - ai/endpoints/microsoft-teams.md #converted
    - ai/endpoints/sunshine-conversations.md #converted
    - ai/endpoints/slack.md #converted
    - ai/endpoints/ringcentral-engage.md #converted
    - ai/endpoints/twilio.md #converted
    - ai/endpoints/userlike.md #converted
    - ai/endpoints/workplace-by-fb.md #converted
  - Installation & Configuration:
    - ai/installation/installation-and-updating.md #converted
    - ai/installation/browser-requirements.md #converted
    - ai/installation/single-signin-SAML2.md #converted
    - ai/installation/single-signin-openID-connect.md #converted
    - ai/installation/IP-ranges-shared-environments.md #converted
  - Developer Guides:
    - ai/developer-guides/api-reference.md #converted
    - ai/developer-guides/using-api.md #converted
    - ai/developer-guides/clients.md #converted
  - Help & Contact:
    - ai/help/get-help.md #converted
    - ai/help/community.md #converted
- Insights:
  - insights/cognigy-insights.md #converted
  - insights/global-filter.md #converted
  - insights/dashboard-overview.md #converted
  - insights/dashboard-engagement.md #converted
  - insights/dashboard-nlu-performance.md #converted
  - insights/step-explorer.md
  - insights/transcript-explorer.md
  - insights/message-explorer.md
  - insights/download-report.md #converted
- Webchat Widget:
  - ai/endpoints/webchat/webchat.md  #converted
  - ai/endpoints/webchat/webchat.md #converted
  - ai/endpoints/webchat/deploy-webchat-endpoint.md #converted
  - ai/endpoints/webchat/webchat-features.md #converted
  - ai/endpoints/webchat/triggering-webchat-plugins.md #converted
  - ai/endpoints/webchat/integrated-demo-page.md #converted
- Live Agent:
  - live-agent/platform-overview.md
  - Release Notes:
    - live-agent/release-notes/releases.md
  - Getting started:
    - Creating an account:
      - live-agent/getting-started/creating-an-account.md
    - Inviting your agents:
      - live-agent/getting-started/inviting-your-agents.md
    - Add an inbox:
      - live-agent/getting-started/add-an-inbox.md
    - Handover flow with Cognigy.AI:
      - live-agent/getting-started/handover-flow-with-cognigy-ai.md
    - Add Teams:
      - live-agent/getting-started/add-teams.md
    - Add label:
      - live-agent/getting-started/add-label.md
  - Installation & configuration:
    - Deployment:
      - Prerequisites:
        - live-agent/installation/prerequisites.md
      - Architecture:
        - live-agent/installation/architecture.md
    - Installation using Helm:
      - live-agent/installation/installation-using-helm.md
    - Installation updates:
      - live-agent/installation/installation-updates.md
    - Configuration/Tweaking:
      - Database:
        - live-agent/installation/configuration/database.md
      - Redis:
        - live-agent/installation/configuration/redis.md
      - Mail:
        - live-agent/installation/configuration/mail.md
  - Agent:
    - live-agent/agent.md
  - Contacts:
    - live-agent/contacts.md
  - Reports:
    - live-agent/reports.md
  - Settings:
    - live-agent/settings.md
  - Help & Support:
    - live-agent/help.md
- Marketplace:
  - ai/resources/manage/extensions#marketplace
- Usage:
  - usage-doc.md
markdown_extensions:
- toc:
    permalink: true
    slugify: !!python/name:pymdownx.slugs.uslugify ''
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed
- abbr
- admonition
- attr_list
- def_list
- footnotes
- meta
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
- pymdownx.critic:
    mode: view
extra:
  generator: false
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/cognigy
    name: Cognigy on Twitter
  - icon: fontawesome/brands/facebook
    link: https://www.facebook.com/cognigy/
    name: Cognigy on Facebook
  - icon: fontawesome/brands/github
    link: https://github.com/Cognigy
    name: Cognigy on GitHub
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/cognigy/mycompany/
    name: Cognigy on LinkedIn
  - icon: fontawesome/brands/youtube
    link: https://www.youtube.com/c/Cognigy
    name: Cognigy on YouTube
  alternate:
  - link: /
    name: en
extra_css:
- assets/css/extra.css
extra_javascript:
- assets/js/termynal.js
- assets/js/custom.js
plugins:
- section-index
- macros
- search
