site_name: Cognigy.AI
site_description: Documentation from Cognigy.AI products
site_url: http://127.0.0.1:8008/de/
theme:
  name: material
  custom_dir: overrides
  palette:
  - scheme: default
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  font:
    text: Mulish
  features:
  - search.suggest
  - search.highlight
  - navigation.tabs
  - navigation.tracking
  - navigation.indexes
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  logo: http://127.0.0.1:8008/img/Cognigy-white.svg
  favicon: http://127.0.0.1:8008/img/favicon.png
  language: de
nav:
- Cognigy Produkte: index.md
- AI:
  - ai/platform-overview.md
  - Versionshinweise:
    - ai/release-notes/4.8.0.md
  - Ressourcen:
    - Agenten:
      - ai/resources/agents/agents.md
      - ai/resources/agents/journeys.md
      - ai/resources/agents/tasks.md
    - Bauen:
      - ai/resources/build/build.md
      - ai/resources/build/flows.md
      - ai/resources/build/lexicons.md
      - ai/resources/build/connections.md
      - ai/resources/build/nlu-connectors.md
      - ai/resources/build/functions.md
    - Einsetzen:
      - ai/resources/deploy/endpoints.md
      - ai/resources/deploy/snapshots.md
    - Testen:
      - ai/resources/test/playbooks.md
      - ai/resources/test/logs.md
    - Optimieren:
      - ai/resources/tweak/intent-trainer.md
    - Statistiken:
      - ai/resources/analytics.md
    - Verwalten:
      - ai/resources/manage/settings.md
      - ai/resources/manage/localization.md
      - ai/resources/manage/tokens.md
      - ai/resources/manage/extensions.md
      - ai/resources/manage/members.md
      - ai/resources/manage/contact-profiles.md
      - ai/resources/manage/packages.md
  - Flow Nodes:
    - ai/flow-nodes/flow-nodes-overview.md
    - ai/flow-nodes/node-usage.md
    - ai/flow-nodes/dynamic-content.md
    - Nachrichten:
      - ai/flow-nodes/message/message.md
      - ai/flow-nodes/message/say.md
      - ai/flow-nodes/message/question.md
      - ai/flow-nodes/message/optional-question.md
      - ai/flow-nodes/message/send-email.md
      - ai/flow-nodes/message/send-email-notification.md
      - ai/flow-nodes/message/send-text.md
      - ai/flow-nodes/message/datepicker.md
    - Logik:
      - ai/flow-nodes/logic/if.md
      - ai/flow-nodes/logic/lookup.md
      - ai/flow-nodes/logic/go-to.md
      - ai/flow-nodes/logic/execute-flow.md
      - ai/flow-nodes/logic/think.md
      - ai/flow-nodes/logic/once.md
      - ai/flow-nodes/logic/interval.md
      - ai/flow-nodes/logic/stop-and-return.md
      - ai/flow-nodes/logic/wait-for-input.md
      - ai/flow-nodes/logic/sleep.md
      - ai/flow-nodes/logic/reset-state.md
      - ai/flow-nodes/logic/disable-slot-fillers.md
      - ai/flow-nodes/logic/set-state.md
      - ai/flow-nodes/logic/enable-slot-fillers.md
      - ai/flow-nodes/logic/add-to-context.md
      - ai/flow-nodes/logic/remove-from-context.md
      - ai/flow-nodes/logic/switch-locale.md
      - ai/flow-nodes/logic/trigger-function.md
    - Profil:
      - ai/flow-nodes/profile/update-profile.md
      - ai/flow-nodes/profile/deactivate-profile.md
      - ai/flow-nodes/profile/delete-profile.md
      - ai/flow-nodes/profile/activate-profile.md
      - ai/flow-nodes/profile/merge-profile.md
      - ai/flow-nodes/profile/complete-goal.md
    - Dienstleistungen:
      - ai/flow-nodes/services/ms-sql.md
      - ai/flow-nodes/services/mongo-db.md
      - ai/flow-nodes/services/http-request.md
    - NLU:
      - ai/flow-nodes/nlu/copy-slots-to-context.md
      - ai/flow-nodes/nlu/add-lexicon-keyphrase.md
      - ai/flow-nodes/nlu/execute-cognigy-nlu.md
      - ai/flow-nodes/nlu/regex-slotfiller.md
    - Code:
      - ai/flow-nodes/code/code.md
      - ai/flow-nodes/code/actions.md
      - ai/flow-nodes/code/modules.md
      - ai/flow-nodes/code/channel-output.md
      - ai/flow-nodes/code/ai-default-channel-formats.md
      - ai/flow-nodes/code/analytics-data.md
    - Voice Gateway:
      - ai/flow-nodes/vg/send-message.md
      - ai/flow-nodes/vg/set-session-params.md
      - ai/flow-nodes/vg/play-url.md
      - ai/flow-nodes/vg/handoverVG.md
      - ai/flow-nodes/vg/hangup.md
      - ai/flow-nodes/vg/send-meta-data.md
      - ai/flow-nodes/vg/call-recording.md
      - ai/flow-nodes/vg/agent-assist.md
    - Andere Nodes:
      - ai/flow-nodes/other-nodes/log-message.md
      - ai/flow-nodes/other-nodes/overwrite-analytics.md
  - NLU:
    - ai/nlu/overview.md
    - NLU Überblick:
      - ai/nlu/nlu-overview/ml-intents.md
      - ai/nlu/nlu-overview/annotations.md
      - ai/nlu/nlu-overview/intent-analyzer.md
      - ai/nlu/nlu-overview/rule-intents.md
      - ai/nlu/nlu-overview/intent-hierarchy.md
      - ai/nlu/nlu-overview/trigger-intent.md
      - ai/nlu/nlu-overview/intent-upload-download.md
      - ai/nlu/nlu-overview/reject-intents.md
    - Slot Mapping:
      - ai/nlu/slot-mapping/any-slots.md
    - Anhänge:
      - ai/nlu/attachments/attached-flows.md
      - ai/nlu/attachments/attached-lexicons.md
    - Externer NLU:
      - ai/nlu/external-nlu/nlu-transformers.md
      - ai/nlu/external-nlu/no-nlu.md
    - ai/nlu/language-support.md
    - ai/nlu/nlu-warnings.md
  - Werkzeuge:
    - ai/tools/overview.md
    - Nutzer Menu:
      - ai/tools/user-menu/my-profile.md
      - ai/tools/user-menu/access-control.md
      - ai/tools/user-menu/usage-statistics.md
    - Interaktionsfeld:
      - ai/tools/interaction-panel/input.md
      - ai/tools/interaction-panel/state.md
      - ai/tools/interaction-panel/context.md
      - ai/tools/interaction-panel/profile.md
    - ai/tools/cognigy-script.md
    - Statistiken:
      - ai/tools/analytics/agents-analytics.md
      - ai/tools/analytics/odata-analytics-endpoint.md
      - ai/tools/analytics/analytics-concepts.md
    - ai/tools/hotkeys.md
    - ai/tools/managementUI.md
    - ai/tools/agent-handover.md
    - ai/tools/live-agent.md
  - Endpunkte:
    - ai/endpoints/overview.md
    - ai/endpoints/data-protection-and-analytics.md
    - ai/endpoints/session-management.md
    - ai/endpoints/handover-settings.md
    - Transformer:
      - ai/endpoints/transformers/input-transformer.md
      - ai/endpoints/transformers/output-transformer.md
      - ai/endpoints/transformers/execution-finished-transformer.md
      - ai/endpoints/transformers/notify-transformer.md
      - ai/endpoints/transformers/inject-transformer.md
    - ai/endpoints/inject-and-notify.md
    - Cognigy Webchat:
      - ai/endpoints/webchat/webchat.md
      - ai/endpoints/webchat/deploy-webchat-endpoint.md
      - ai/endpoints/webchat/webchat-features.md
      - ai/endpoints/webchat/triggering-webchat-plugins.md
      - ai/endpoints/webchat/integrated-demo-page.md
    - ai/endpoints/cognigy-vg.md
    - ai/endpoints/rest.md
    - ai/endpoints/socketio.md
    - ai/endpoints/webhook.md
    - ai/endpoints/amazon-alexa.md
    - ai/endpoints/dialogflow.md
    - ai/endpoints/facebook-messenger.md
    - ai/endpoints/google-actions.md
    - ai/endpoints/intercom.md
    - ai/endpoints/line-messenger.md
    - ai/endpoints/azure-bot-services.md
    - ai/endpoints/microsoft-teams.md
    - ai/endpoints/ringcentral-engage.md
    - ai/endpoints/twilio.md
    - ai/endpoints/userlike.md
    - ai/endpoints/workplace-by-fb.md
  - Installation & Konfiguration:
    - ai/installation/installation-and-updating.md
    - ai/installation/browser-requirements.md
    - ai/installation/single-signin-SAML2.md
    - ai/installation/single-signin-openID-connect.md
    - ai/installation/IP-ranges-shared-environments.md
  - Entwicklerhandbücher:
    - ai/developer-guides/api-reference.md
    - ai/developer-guides/using-api.md
    - ai/developer-guides/clients.md
  - Hilfe & Kontakt:
    - ai/help/community.md
    - ai/help/get-help.md
- Insights:
  - insights/index.md
- Webchat:
  - webchat/index.md
- Live Agent:
  - live-agent/index.md
- Usage:
  - usage-doc.md
markdown_extensions:
- toc:
    permalink: true
    slugify: !!python/name:pymdownx.slugs.uslugify ''
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed
- abbr
- admonition
- attr_list
- def_list
- footnotes
- meta
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
- pymdownx.critic:
    mode: view
extra:
  generator: false
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/cognigy
    name: Cognigy on Twitter
  - icon: fontawesome/brands/facebook
    link: https://www.facebook.com/cognigy/
    name: Cognigy on Facebook
  - icon: fontawesome/brands/github
    link: https://github.com/Cognigy
    name: Cognigy on GitHub
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/cognigy/mycompany/
    name: Cognigy on LinkedIn
  - icon: fontawesome/brands/youtube
    link: https://www.youtube.com/c/Cognigy
    name: Cognigy on YouTube
  alternate:
  - link: /
    name: en
  - link: /de/
    name: de
extra_css:
- http://127.0.0.1:8008/css/extra.css
extra_javascript:
- http://127.0.0.1:8008/js/termynal.js
- http://127.0.0.1:8008/js/custom.js
plugins:
- section-index
- macros
- search
