name: documentation

trigger:
  batch: "true"
  branches:
    include:
      - "main"

pr:
  branches:
    include:
      - "main"

resources:
  - repo: self

variables:
  DOCKER_BUILDKIT: 1
  containerRegistryReference: "Azure Container Registry"
  imageName: "documentation"

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: BuildLastChanges
    displayName: Generate Last Changes and Build Documentation
    jobs:
      - job:
        displayName: Generate Last Changes List
        steps:
          # Checkout code with full history to ensure git log works
          - checkout: self
            persistCredentials: "true"
            clean: "true"
            fetchDepth: 0

          # Grant execute permissions to the script
          - script: chmod +x ./generate-last-changes-list.sh
            displayName: Grant execute permissions to the script

          # Execute the script
          - script: ./generate-last-changes-list.sh
            displayName: Run script to generate last changes list

          # Optionally, publish the output file as a pipeline artifact
          - task: PublishBuildArtifacts@1
            displayName: Publish changes list
            inputs:
              PathtoPublish: $(System.DefaultWorkingDirectory)/file_changes_all.txt
              ArtifactName: last-changes-list

  - stage: Build
    displayName: Build product documentation
    jobs:
      - job:
        displayName: Build product documentation
        steps:
          - task: Docker@2
            displayName: Login to Docker-Registry
            inputs:
              command: "login"
              containerRegistry: $(containerRegistryReference)

          - task: Docker@2
            displayName: Build and push container image
            inputs:
              command: "buildAndPush"
              repository: $(imageName)
              buildContext: .
              dockerfile: "./build/Dockerfile"
              containerRegistry: $(containerRegistryReference)
              tags: main-$(Build.BuildId)
