name: build-vale-linter

trigger:
  - none # Disable automatic triggers on branches.

pr:
  - task/86067-vg-settings # Trigger pipeline on a specific Pull Request.

pool:
  vmImage: ubuntu-20.04

steps:
  # Step 1: Identify Modified Files in the PR
  - script: |
      echo "Fetching target branch and identifying modified Markdown files..."
      echo "Target Branch: $(System.PullRequest.TargetBranch)"
      echo "Source Branch: $(System.PullRequest.SourceBranch)"
      
      mkdir -p vale_bin
      git fetch origin $(System.PullRequest.TargetBranch) || exit 1
      git diff --name-only origin/$(System.PullRequest.TargetBranch)..$(System.PullRequest.SourceBranch) | grep -E '\.md$' > filtered_files.txt || true
    displayName: 'Identify Modified Files'

  # Step 2: Run Vale on Filtered Files Using Docker
  - script: |
      echo "Running Vale on modified Markdown files..."
      FILTERED_FILES=$(cat filtered_files.txt)
      if [ -z "$FILTERED_FILES" ]; then
        echo "No Markdown files to lint. Skipping."
        exit 0
      fi

      echo "$FILTERED_FILES" > file_list.txt
      docker run --rm -v $(pwd)/styles:/styles \
                 -v $(pwd):/workspace \
                 -w /workspace \
                 jdkato/vale $(cat file_list.txt) --output=JSON > vale-report.json || exit 1
      echo "Vale linting completed. Report saved to vale-report.json."
    displayName: 'Run Vale Linter with Docker'

  # Step 3: Publish Vale Report as Artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'vale-report.json'
      artifactName: 'vale-report'
    displayName: 'Publish Vale Report Artifact'

  # Step 4: Post Artifact Link as PR Comment
  - script: |
      echo "Generating artifact URL and posting as PR comment..."
      ARTIFACT_URL="$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_apis/build/builds/$(Build.BuildId)/artifacts?artifactName=vale-report&api-version=6.0-preview.1"
      
      COMMENT_BODY="### Vale Linter Report%0AThe Vale report is available [here]($ARTIFACT_URL)."
      
      curl -X POST -H "Authorization: Bearer $(System.AccessToken)" \
        -H "Content-Type: application/json" \
        -d "{\"comments\": [{\"content\": \"$COMMENT_BODY\"}]}" \
        "$(System.CollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=7.1-preview.1" || exit 1
    displayName: 'Post Artifact Link as PR Comment'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)