name: generate-last-changes-list

trigger:
  batch: true
  branches:
    include:
      - "main"

resources:
  - repo: self

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: BuildLastChanges
    displayName: Generate Last Changes Lists
    jobs:
      - job:
        displayName: Generate Last Changes List
        steps:
          - checkout: self
            persistCredentials: "true"
            clean: true
            fetchDepth: 0
            fetchTags: true

          - script: |
              mkdir -p $(Build.SourcesDirectory)/docs/_assets/last_changes
              chmod 755 $(Build.SourcesDirectory)/docs/_assets/last_changes
            displayName: Set permissions on last_changes directory

          - script: |
              git config --global --add safe.directory $(Build.SourcesDirectory)
              chmod +x ./docs/_assets/generate-last-changes-list.sh
            displayName: Configure Git and grant execute permissions

          - script: ./docs/_assets/generate-last-changes-list.sh
            displayName: Run script to generate last changes list

          - script: ls -R $(Build.SourcesDirectory)
            displayName: List all files and directories

          - script: find $(Build.SourcesDirectory) -name "file_changes_all.txt"
            displayName: Find generated file

          - task: PublishBuildArtifacts@1
            displayName: Publish changes list
            inputs:
              PathtoPublish: $(Build.SourcesDirectory)/docs/_assets/last_changes/file_changes_all.txt
              ArtifactName: last-changes-list
